// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration for Smart Health Tracker
/// Project ID: project-566847679576
/// 
/// TODO: Run `flutterfire configure` to replace these placeholders with real values.
/// CRITICAL: Data persistence will FAIL until you replace these placeholders.
/// Steps:
///   1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
///   2. Run: flutterfire configure --project=project-566847679576
///   3. This file will be auto-generated with correct values.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with real values from Firebase Console

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_pwO-9_k44MIBBUfWapYOcjjb7123UQg',
    appId: '1:566847679576:web:2cf5015c26bb31ca106e2d',
    messagingSenderId: '566847679576',
    projectId: 'smart-health-tracker-app',
    authDomain: 'smart-health-tracker-app.firebaseapp.com',
    storageBucket: 'smart-health-tracker-app.firebasestorage.app',
    measurementId: 'G-E9VZFF5GEN',
  );

  // Project: project-566847679576 (Smart Health Tracker App)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFiymPRJn6fhMDGAs9NNetzSxGPCy6XAo',
    appId: '1:566847679576:android:de4862552e4e3b79106e2d',
    messagingSenderId: '566847679576',
    projectId: 'smart-health-tracker-app',
    storageBucket: 'smart-health-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0xQml1wjXIOvmJXl9EwcBckgb0O-ZpvE',
    appId: '1:566847679576:ios:81f90b3be1f91a67106e2d',
    messagingSenderId: '566847679576',
    projectId: 'smart-health-tracker-app',
    storageBucket: 'smart-health-tracker-app.firebasestorage.app',
    iosClientId: '566847679576-6rvpiaatku7dt0m7qk6faihls3asc0dr.apps.googleusercontent.com',
    iosBundleId: 'com.healthtracker.smartHealthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_MACOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'project-566847679576',
    storageBucket: 'project-566847679576.firebasestorage.app',
    iosBundleId: 'com.healthtracker.smart_health_tracker',
  );
}