// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration for Smart Health Tracker
/// Project ID: project-566847679576
/// 
/// TODO: Run `flutterfire configure` to replace these placeholders with real values.
/// CRITICAL: Data persistence will FAIL until you replace these placeholders.
/// Steps:
///   1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
///   2. Run: flutterfire configure --project=project-566847679576
///   3. This file will be auto-generated with correct values.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with real values from Firebase Console
  // Project: project-566847679576 (Smart Health Tracker App)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: 'REPLACE_WITH_YOUR_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'project-566847679576',
    authDomain: 'project-566847679576.firebaseapp.com',
    storageBucket: 'project-566847679576.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3OlfpJFZ7bk-LlSsSgTmGk2SHr178EI',
    appId: '1:506718619542:android:15126bebf2f60f48a47fb7',
    messagingSenderId: '506718619542',
    projectId: 'smart-health-tracker-app-11471',
    storageBucket: 'smart-health-tracker-app-11471.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMTPu-sjqos-BC26WvuKXBArb-yfbqk_A',
    appId: '1:506718619542:ios:21e32e1a6f158106a47fb7',
    messagingSenderId: '506718619542',
    projectId: 'smart-health-tracker-app-11471',
    storageBucket: 'smart-health-tracker-app-11471.firebasestorage.app',
    iosClientId: '506718619542-2qm1t7b8vm1pf17qd28p5kcj3n4viskn.apps.googleusercontent.com',
    iosBundleId: 'com.healthtracker.smartHealthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_MACOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'project-566847679576',
    storageBucket: 'project-566847679576.firebasestorage.app',
    iosBundleId: 'com.healthtracker.smart_health_tracker',
  );
}